dist: xenial
language: node_js
node_js:
- node
services:
  - xvfb
cache: npm
install:
- npm i
script:
- xvfb-run --auto-servernum npm test
deploy:
  email:
    secure: Zl2ZhAToi4TySlvClw77LsWByM+luBUKmuG9Dwqo7f5bYrqUGzvfH8s2qOciSUMwhsybFE5C+PuxmnVO4sEgX6v7Ps0MqLsvC5vLud0VyP+WMfezL+zonCq7IRe02ASfGHDI75NYZ0jHyMHyD39Qw6JB6lfrPfhyIWoTM6gRWDvNeoWumkTGRdEpEh7gjMNyv428WIUblpL9QX1p4avaR0EXQHnrWXC6S2y2u5Rc0XAbVyawSUCwwAx+wdGxvvk3GNeIvUHeAvu/1oK1F2OTpC4r5i/InTusPrCfBHR93ysLFGSDoOLDOmeByobrF3OdYLe4neLP3M25cQ7D+3ygfSIDconcs+N569cajltINWKaDVrP8B3xe4Jvq6UvfrbHr/Yb5V9p+NvTl422cSx3SmJJG7KZabhGwkYkjpkDH079l+i9mZYo+qWVwf4iYNew7kleKzg9dHSoWmLRwkqDKC1H0berKAvU2lZ4XORwSYyWzYt04khYzuQwZl4qpWjLP66lRw5M4eqVUUyzE7gpp6URnY1GNCOE8PrIS0RLGzD/uq3Sse17Fe4MZkjvEn0/qlaDcf4+fKJKnw4fpJgdR66WoMqf0k2neUCPwbyR8lgXCCE13+VO/sI777AcA5qPqSaV9Fbskjb7yBlu4CBJ1gq3w2C8rZWOU9MY+UDSIZg=
  api_key:
    secure: Y7MR6Z8oTRwoh2EqSUo1Ytlj90BzSvY+1MRX0CvKNSmZhuchPxvbIliS8FfJgDRUYBX5qZcHu4c4GxesgAEsE/U3BfaqrEKMdt90p6KNaad7MnYAL6BL5cXbMUjvlU+PX62td1OlDIwu8y+jp+BGFZBdnHQ/Blv91FugwwKeVHAArHoJV7YDnSWqcorcpdl4KOCbIErmdd2kj1lTMOV6/3aM3IZqpptnryp8c2/dvGmZ+T+CN1iy21ztSy2vU9DY7+c6DIIbPdw2cCce9wcyLNWZsA4y6Etussmd2u/DHDU7RgSOvQVDdt4YdVd9ceWoH8MC8qxEu8xjvp68ROePnILarttz2ss2rAvs4q0y2bKmGJJQ8r4wBOPJto1QFSqflDWWIYx4BT/encBfH6GoaOEc/Ec/cxh7e307mheWSeyImVekSH/ZNkviIrWM7JkGws/1uFxUQuZzM1cujjSekkaSf9vA/AdxwYraNyGD2Tn4rHABe3pOJJT4iGU5r6y8JstceJJ3hk2GS6H58CaTTjAhovP5Ql2ZgTq7DvixZuLtw/Ay6g0qN8A9svYGewoVKLi9ECCIRuQrH8bPa51afw1uc10wc8zufetRNNUxhNPfmEAPbvvjakOhFgO7w9V2pRoavMk11h2506Rc2vBDZNuTvblUHpfUwNcT/2RMYTY=
  provider: npm
  on:
    tags: true
